# Generated by Django 5.1.7 on 2025-03-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=255)),
                ('appointment_status', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('date_added', models.DateTimeField()),
                ('calendar_name', models.CharField(max_length=255)),
                ('assigned_to', models.CharField(max_length=255)),
                ('contact_id', models.CharField(max_length=100)),
                ('sort_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('sort_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('appointment_owner', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-sort_timestamp'],
            },
        ),
    ]
