# Generated by Django 5.1.7 on 2025-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_currency', models.CharField(max_length=10)),
                ('campaign_id', models.CharField(max_length=50, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('cpc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('account_id', models.CharField(max_length=50)),
                ('conversions', models.IntegerField()),
                ('cost_per_conversion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
