# Generated by Django 5.1.7 on 2025-03-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_facebookcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_resource_name', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=10)),
                ('campaign_resource_name', models.CharField(max_length=255, unique=True)),
                ('campaign_id', models.CharField(max_length=50, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('clicks', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('interactions', models.IntegerField()),
                ('conversions', models.FloatField()),
                ('cost_micros', models.BigIntegerField()),
                ('cost_per_conversion', models.FloatField(blank=True, null=True)),
                ('ctr', models.FloatField()),
                ('avg_cpc', models.FloatField()),
                ('conversion_rate', models.FloatField()),
                ('view_through_conversions', models.IntegerField()),
            ],
            options={
                'db_table': 'googlecampaign',
            },
        ),
    ]
