# Generated by Django 5.1.7 on 2025-03-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_googlecampaign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleCampaign',
        ),
    ]
