# Generated by Django 5.1.7 on 2025-03-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_googlecampaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlecampaign',
            old_name='data',
            new_name='date',
        ),
    ]
