# Generated by Django 5.1.7 on 2025-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_data_googlecampaign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecampaign',
            name='campaign_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='googlecampaign',
            name='campaign_resource_name',
            field=models.CharField(max_length=255),
        ),
    ]
