# Generated by Django 5.1.7 on 2025-03-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_googlecampaign_campaign_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('account_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=50, null=True)),
                ('call_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('call_status', models.CharField(blank=True, max_length=20, null=True)),
                ('called', models.CharField(blank=True, max_length=20, null=True)),
                ('called_city', models.CharField(blank=True, max_length=50, null=True)),
                ('called_country', models.CharField(blank=True, max_length=10, null=True)),
                ('called_state', models.CharField(blank=True, max_length=10, null=True)),
                ('called_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('caller', models.CharField(blank=True, max_length=20, null=True)),
                ('caller_city', models.CharField(blank=True, max_length=50, null=True)),
                ('caller_country', models.CharField(blank=True, max_length=10, null=True)),
                ('caller_state', models.CharField(blank=True, max_length=10, null=True)),
                ('caller_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('from_city', models.CharField(blank=True, max_length=50, null=True)),
                ('from_country', models.CharField(blank=True, max_length=10, null=True)),
                ('from_state', models.CharField(blank=True, max_length=10, null=True)),
                ('from_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('location_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('to_number', models.CharField(blank=True, max_length=20, null=True)),
                ('to_city', models.CharField(blank=True, max_length=50, null=True)),
                ('to_country', models.CharField(blank=True, max_length=10, null=True)),
                ('to_state', models.CharField(blank=True, max_length=10, null=True)),
                ('to_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('first_time', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'callreport',
            },
        ),
    ]
