# Generated by Django 5.1.7 on 2025-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_budget_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
