# Generated by Django 5.1.7 on 2025-03-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_location_id_opportunity_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCampaignTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_conversions', models.FloatField(blank=True, null=True)),
                ('avg_cpc', models.FloatField(blank=True, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('conversion_rate', models.FloatField(blank=True, null=True)),
                ('conversions', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('cost_per_conversion', models.FloatField(blank=True, null=True)),
                ('impressions', models.IntegerField(blank=True, null=True)),
                ('interactions', models.IntegerField(blank=True, null=True)),
                ('view_through_conversions', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'googlecampaigntotal',
            },
        ),
    ]
