# Generated by Django 5.1.7 on 2025-03-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_googlecampaigntotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppointment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.CharField(blank=True, max_length=50, null=True)),
                ('calendar_name', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sort', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('appointment_owner', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'userappointment',
            },
        ),
    ]
