# Generated by Django 5.1.7 on 2025-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='appointment_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userappointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
