# Generated by Django 5.1.7 on 2025-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userappointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointment',
            name='appointment_id',
            field=models.CharField(max_length=50),
        ),
    ]
