# Generated by Django 5.1.7 on 2025-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_ghlauthcredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='business_name',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, default='No Data', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='No Data', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.TextField(blank=True, default='No Data', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='utm_campaign',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='utm_content',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='utm_medium',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='utm_source',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='utm_term',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='utm_traffic_type',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
    ]
