# Generated by Django 5.1.7 on 2025-04-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_contact_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='assigned',
            field=models.CharField(default='No Data', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='days_since_last_updated',
            field=models.CharField(default='No Data', max_length=50),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='followers',
            field=models.TextField(default='No Data'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lost_reason_id',
            field=models.CharField(default='No Data', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lost_reason_name',
            field=models.CharField(default='No Data', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='notes',
            field=models.TextField(default='No Data'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='sq_ft',
            field=models.CharField(default='No Data', max_length=50),
        ),
    ]
