# Generated by Django 5.1.7 on 2025-04-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_opportunity_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='assigned',
            field=models.CharField(blank=True, default='No Data', max_length=255),
        ),
    ]
