# Generated by Django 5.1.7 on 2025-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_opportunity_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='assigned',
            field=models.CharField(blank=True, default='No Data', max_length=255, null=True),
        ),
    ]
