# Generated by Django 5.1.7 on 2025-04-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_opportunity_lost_reason_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=255, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
