# Generated by Django 5.1.7 on 2025-04-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_webhooklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhooklog',
            name='webhook_id',
        ),
    ]
