# Generated by Django 5.1.7 on 2025-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_webhooklog_webhook_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(default=0)),
                ('change_percentage', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
