# Generated by Django 5.1.7 on 2025-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
