# Generated by Django 5.1.7 on 2025-04-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='change_percentage',
            new_name='clicked_change_percentage',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='count',
            new_name='clicked_count',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='status',
            new_name='clicked_status',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='change_percentage',
            new_name='clicked_change_percentage',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='count',
            new_name='clicked_count',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='status',
            new_name='clicked_status',
        ),
        migrations.AddField(
            model_name='email',
            name='count_change_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='count_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='count_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='opened_change_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='opened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='opened_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='replied_change_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='replied_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='replied_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='delivered_change_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='delivered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='delivered_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='failed_change_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='failed_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='sent_change_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sms',
            name='sent_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
